import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// Utility function to format currency for PDF (with proper encoding)
const formatCurrency = (amount) => {
  // Handle null, undefined, and NaN values
  if (amount === null || amount === undefined || isNaN(amount) || amount === '') {
    return 'N 0.00';
  }
  
  // Convert to number and handle edge cases
  const numAmount = parseFloat(amount);
  if (isNaN(numAmount)) {
    return 'N 0.00';
  }
  
  return `N ${numAmount.toLocaleString('en-NG', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

// Utility function to format percentage
const formatPercentage = (rate) => {
  if (rate === null || rate === undefined || isNaN(rate) || rate === '') {
    return '0.00%';
  }
  
  const numRate = parseFloat(rate);
  if (isNaN(numRate)) {
    return '0.00%';
  }
  
  return `${(numRate * 100).toFixed(2)}%`;
};

// Utility function to format date
const formatDate = () => {
  return new Date().toLocaleDateString('en-NG', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
};

// Add taxpayer-focused header
const addTaxpayerHeader = (doc, title, taxpayerInfo) => {
  // Document title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text(title, 20, 20);
  
  // Taxpayer Information Section
  let yPos = 35;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Taxpayer Information', 20, yPos);
  yPos += 8;
  
  // Create taxpayer info table
  const taxpayerData = [];
  if (taxpayerInfo.name) {
    taxpayerData.push(['Taxpayer Name:', taxpayerInfo.name]);
  }
  if (taxpayerInfo.tin) {
    taxpayerData.push(['Tax ID (TIN):', taxpayerInfo.tin]);
  }
  if (taxpayerInfo.month) {
    taxpayerData.push(['Period/Month:', taxpayerInfo.month]);
  }
  if (taxpayerInfo.year) {
    taxpayerData.push(['Year of Assessment:', taxpayerInfo.year]);
  }
  if (taxpayerInfo.state) {
    taxpayerData.push(['State of Residence:', taxpayerInfo.state]);
  }
  if (taxpayerInfo.tax_authority) {
    taxpayerData.push(['Tax Authority:', taxpayerInfo.tax_authority]);
  }
  if (taxpayerInfo.employer_contact) {
    taxpayerData.push(['Employer Contact:', taxpayerInfo.employer_contact]);
  }
  if (taxpayerInfo.employer_address) {
    taxpayerData.push(['Employer Address:', taxpayerInfo.employer_address]);
  }
  
  // Add taxpayer info table
  if (taxpayerData.length > 0) {
    autoTable(doc, {
      startY: yPos,
      head: [],
      body: taxpayerData,
      theme: 'plain',
      styles: {
        fontSize: 10,
        cellPadding: 2
      },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 50 },
        1: { cellWidth: 100 }
      },
      margin: { left: 20, right: 20 } // Add proper margins to align with rest of document
    });
    yPos = doc.lastAutoTable.finalY + 10;
  }
  
  // Generated date
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on: ${formatDate()}`, 20, yPos);
  
  // Return the Y position where content should start
  return yPos + 15;
};

// Add Fiquant footnote footer
const addFiquantFooter = (doc) => {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // Add separator line
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 275, 190, 275);
    
    // Fiquant branding footnote
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by Fiquant TaxPro - Nigerian Tax Calculator 2026', 20, 282);
    doc.text('© 2025 Fiquant Consult. All rights reserved.', 20, 287);
    
    // Page number
    doc.text(`Page ${i} of ${pageCount}`, 170, 287);
  }
};

// Generate Single PAYE Report
export const generatePayeReport = (taxInput, result) => {
  const doc = new jsPDF();
  
  // Prepare taxpayer info for header
  const taxpayerInfo = {
    name: taxInput.staff_name || 'Not specified',
    tin: taxInput.tin || null,
    month: taxInput.month || 'Not specified',
    year: taxInput.year || 'Not specified',
    state: taxInput.state_of_residence || 'Not specified',
    tax_authority: taxInput.tax_authority || null
  };
  
  let yPos = addTaxpayerHeader(doc, 'PAYE Tax Calculation Report', taxpayerInfo);
  
  // Remove the redundant Staff Information Section since it's now in header
  
  // Income Details Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Income Details (Monthly)', 20, yPos);
  yPos += 10;
  
  // Income Details Table - now includes all allowance types
  const incomeData = [
    ['Basic Salary', formatCurrency(taxInput.basic_salary)],
    ['Transport Allowance', formatCurrency(taxInput.transport_allowance)],
    ['Housing Allowance', formatCurrency(taxInput.housing_allowance)],
    ['Meal Allowance', formatCurrency(taxInput.meal_allowance)],
    ['Utility Allowance', formatCurrency(taxInput.utility_allowance)],
    ['Medical Allowance', formatCurrency(taxInput.medical_allowance)],
    ['Other Allowances', formatCurrency(taxInput.other_allowances)],
    ['Monthly Gross Income', formatCurrency(result.monthly_gross_income)]
  ];
  
  autoTable(doc, {
    head: [['Income Component', 'Amount']],
    body: incomeData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Relief & Deductions Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Monthly Reliefs & Deductions', 20, yPos);
  yPos += 10;
  
  const reliefData = [
    ['Pension Contribution (8%)', formatCurrency(taxInput.pension_contribution || result.monthly_gross_income * 0.08)],
    ['NHF Contribution (2.5%)', formatCurrency(taxInput.nhf_contribution || result.monthly_gross_income * 0.025)],
    ['Life Insurance Premium', formatCurrency(taxInput.life_insurance_premium)],
    ['Health Insurance Premium', formatCurrency(taxInput.health_insurance_premium)],
    ['NHIS Contribution', formatCurrency(taxInput.nhis_contribution)],
    ['Annual Rent Relief', formatCurrency(result.rent_relief || result.annual_rent_relief || 0)],
    ['Mortgage Interest Relief', formatCurrency(taxInput.mortgage_interest || 0)],
    ['Total Monthly Reliefs', formatCurrency(result.total_reliefs)]
  ];
  
  autoTable(doc, {
    head: [['Relief Component', 'Amount']],
    body: reliefData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Tax Calculation Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Tax Calculation Summary', 20, yPos);
  yPos += 10;
  
  const taxData = [
    ['Annual Gross Income', formatCurrency(result.annual_gross_income)],
    ['Annual Total Reliefs', formatCurrency(result.total_reliefs)],
    ['Annual Taxable Income', formatCurrency(result.taxable_income)],
    ['Annual Tax Due', formatCurrency(result.tax_due)],
    ['Effective Tax Rate', formatPercentage(result.effective_tax_rate)],
    ['Monthly Tax (PAYE)', formatCurrency(result.monthly_tax)],
    ['Monthly Net Income', formatCurrency(result.monthly_net_income)]
  ];
  
  autoTable(doc, {
    head: [['Calculation Component', 'Amount']],
    body: taxData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [34, 197, 94], textColor: [255, 255, 255] }, // Green header
    margin: { left: 20, right: 20 }
  });
  
  // Add tax bracket information if available
  if (result.tax_breakdown && result.tax_breakdown.length > 0) {
    yPos = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Tax Bracket Breakdown', 20, yPos);
    yPos += 10;
    
    const bracketData = result.tax_breakdown.map(bracket => {
      // Ensure the range has Naira symbol - replace ₦ with N for PDF font compatibility
      let rangeText = bracket.range || 'N/A';
      // Replace ₦ (Unicode \u20a6) with N for better PDF font compatibility
      rangeText = rangeText.replace(/₦/g, 'N ').replace(/\u20a6/g, 'N ');
      
      return [
        rangeText,
        bracket.rate || '0%',  // rate already includes % from backend
        formatCurrency(bracket.taxable_amount || 0),
        formatCurrency(bracket.tax_amount || 0)
      ];
    });
    
    autoTable(doc, {
      head: [['Income Range', 'Rate', 'Taxable Amount', 'Tax Amount']],
      body: bracketData,
      startY: yPos,
      theme: 'grid',
      headStyles: { fillColor: [59, 130, 246], textColor: [255, 255, 255] }, // Blue header
      margin: { left: 20, right: 20 }
    });
  }
  
  addFiquantFooter(doc);
  
  // Save the PDF
  doc.save(`PAYE_Tax_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};

// Generate Single PAYE Report and return as Base64
export const generatePayeReportAsBase64 = (taxInput, result) => {
  const doc = new jsPDF();
  
  // Prepare taxpayer info for header
  const taxpayerInfo = {
    name: taxInput.staff_name || 'Not specified',
    tin: taxInput.tin || null,
    month: taxInput.month || 'Not specified',
    year: taxInput.year || 'Not specified',
    state: taxInput.state_of_residence || 'Not specified',
    tax_authority: taxInput.tax_authority || null
  };
  
  let yPos = addTaxpayerHeader(doc, 'PAYE Tax Calculation Report', taxpayerInfo);
  
  // Income Details Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Income Details (Monthly)', 20, yPos);
  yPos += 10;
  
  const incomeData = [
    ['Basic Salary', formatCurrency(taxInput.basic_salary)],
    ['Transport Allowance', formatCurrency(taxInput.transport_allowance)],
    ['Housing Allowance', formatCurrency(taxInput.housing_allowance)],
    ['Meal Allowance', formatCurrency(taxInput.meal_allowance)],
    ['Utility Allowance', formatCurrency(taxInput.utility_allowance)],
    ['Medical Allowance', formatCurrency(taxInput.medical_allowance)],
    ['Other Allowances', formatCurrency(taxInput.other_allowances)],
    ['Monthly Gross Income', formatCurrency(result.monthly_gross_income)]
  ];
  
  autoTable(doc, {
    head: [['Income Component', 'Amount']],
    body: incomeData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Relief & Deductions Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Monthly Reliefs & Deductions', 20, yPos);
  yPos += 10;
  
  const reliefData = [
    ['Pension Contribution (8%)', formatCurrency(taxInput.pension_contribution || result.monthly_gross_income * 0.08)],
    ['NHF Contribution (2.5%)', formatCurrency(taxInput.nhf_contribution || result.monthly_gross_income * 0.025)],
    ['Life Insurance Premium', formatCurrency(taxInput.life_insurance_premium)],
    ['Health Insurance Premium', formatCurrency(taxInput.health_insurance_premium)],
    ['NHIS Contribution', formatCurrency(taxInput.nhis_contribution)],
    ['Annual Rent Relief', formatCurrency(result.rent_relief || result.annual_rent_relief || 0)],
    ['Mortgage Interest Relief', formatCurrency(taxInput.mortgage_interest || 0)],
    ['Total Monthly Reliefs', formatCurrency(result.total_reliefs)]
  ];
  
  autoTable(doc, {
    head: [['Relief Component', 'Amount']],
    body: reliefData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Tax Calculation Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Tax Calculation Summary', 20, yPos);
  yPos += 10;
  
  const taxData = [
    ['Annual Gross Income', formatCurrency(result.annual_gross_income)],
    ['Annual Total Reliefs', formatCurrency(result.total_reliefs)],
    ['Annual Taxable Income', formatCurrency(result.taxable_income)],
    ['Annual Tax Due', formatCurrency(result.tax_due)],
    ['Effective Tax Rate', formatPercentage(result.effective_tax_rate)],
    ['Monthly Tax (PAYE)', formatCurrency(result.monthly_tax)],
    ['Monthly Net Income', formatCurrency(result.monthly_net_income)]
  ];
  
  autoTable(doc, {
    head: [['Summary Item', 'Amount']],
    body: taxData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [34, 197, 94], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  addFiquantFooter(doc);
  
  // Return as base64
  return doc.output('datauristring').split(',')[1];
};

// Generate Bulk PAYE Report
export const generateBulkPayeReport = (employees, totals, companyInfo = {}) => {
  const doc = new jsPDF();
  
  // Prepare company info for header
  const headerInfo = {
    name: companyInfo.company_name || 'Not specified',
    tin: companyInfo.company_tin || null,
    month: companyInfo.payroll_month || null,
    year: companyInfo.payroll_year || new Date().getFullYear().toString(),
    tax_authority: companyInfo.tax_authority || null,
    employer_contact: companyInfo.employer_contact || null,
    employer_address: companyInfo.employer_address || null
  };
  
  let yPos = addTaxpayerHeader(doc, 'Bulk PAYE Tax Calculation Report', headerInfo);
  
  // Summary Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Payroll Summary', 20, yPos);
  yPos += 10;
  
  const summaryData = [
    ['Company Name', companyInfo.company_name || 'Not specified'],
    ['Company TIN', companyInfo.company_tin || 'Not specified'],
    ['Tax Authority', companyInfo.tax_authority || 'Not specified'],
    ['Payroll Period', companyInfo.payroll_month && companyInfo.payroll_year 
      ? `${companyInfo.payroll_month} ${companyInfo.payroll_year}` 
      : 'Not specified'],
    ['Total Employees Processed', totals.employeeCount.toString()],
    ['Total Monthly Gross Pay', formatCurrency(totals.totalGross)],
    ['Total Monthly Deductions', formatCurrency(totals.totalDeductions || 0)],
    ['Total Monthly Tax (PAYE)', formatCurrency(totals.totalTax)],
    ['Total Monthly Net Pay', formatCurrency(totals.totalNet)],
    ['Total Annual Tax', formatCurrency(totals.totalTax * 12)]
  ];
  
  autoTable(doc, {
    head: [['Summary Item', 'Amount/Count']],
    body: summaryData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [34, 197, 94], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 20;
  
  // Employee Details Section with expanded columns
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Employee Tax Details', 20, yPos);
  yPos += 10;
  
  const calculatedEmployees = employees.filter(emp => emp.calculated && emp.result);
  
  // Expanded employee data with deductions breakdown
  const employeeData = calculatedEmployees.map((emp, index) => [
    (index + 1).toString(),
    emp.name,
    emp.tin || 'N/A',
    formatCurrency(emp.result.monthly_gross_income),
    formatCurrency(emp.result.total_reliefs || 0),
    formatCurrency(emp.result.monthly_tax),
    formatCurrency(emp.result.monthly_net_income)
  ]);
  
  autoTable(doc, {
    head: [['#', 'Employee Name', 'TIN', 'Monthly Gross', 'Total Deductions', 'Monthly Tax', 'Monthly Net']],
    body: employeeData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 },
    styles: { fontSize: 8 }
  });
  
  // Add individual employee deduction breakdown on new page if more than summary is needed
  if (calculatedEmployees.length > 0 && calculatedEmployees.length <= 10) {
    doc.addPage();
    yPos = 20;
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Individual Deduction Breakdown', 20, yPos);
    yPos += 15;
    
    calculatedEmployees.forEach((emp, index) => {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }
      
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(`${index + 1}. ${emp.name} (TIN: ${emp.tin || 'N/A'})`, 20, yPos);
      yPos += 8;
      
      const empDeductionData = [
        ['Gross Income', formatCurrency(emp.result.monthly_gross_income)],
        ['Pension (8%)', formatCurrency(emp.pension_contribution || emp.result.monthly_gross_income * 0.08)],
        ['NHF (2.5%)', formatCurrency(emp.nhf_contribution || emp.result.monthly_gross_income * 0.025)],
        ['Life Insurance', formatCurrency(emp.life_insurance_premium || 0)],
        ['Health Insurance', formatCurrency(emp.health_insurance_premium || 0)],
        ['NHIS', formatCurrency(emp.nhis_contribution || 0)],
        ['Rent Relief', formatCurrency(emp.annual_rent ? emp.annual_rent / 12 : 0)],
        ['Mortgage Interest', formatCurrency(emp.mortgage_interest || 0)],
        ['Total Deductions', formatCurrency(emp.result.total_reliefs || 0)],
        ['Taxable Income', formatCurrency(emp.result.taxable_income || 0)],
        ['PAYE Tax', formatCurrency(emp.result.monthly_tax)],
        ['Net Income', formatCurrency(emp.result.monthly_net_income)]
      ];
      
      autoTable(doc, {
        body: empDeductionData,
        startY: yPos,
        theme: 'striped',
        styles: { fontSize: 8 },
        columnStyles: {
          0: { cellWidth: 50, fontStyle: 'bold' },
          1: { cellWidth: 40, halign: 'right' }
        },
        margin: { left: 25, right: 100 }
      });
      
      yPos = doc.lastAutoTable.finalY + 15;
    });
  }
  
  addFiquantFooter(doc);
  
  // Generate filename with company name if available
  const companyNameSlug = companyInfo.company_name 
    ? companyInfo.company_name.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 30) + '_'
    : '';
  const periodSlug = companyInfo.payroll_month && companyInfo.payroll_year 
    ? `${companyInfo.payroll_month}_${companyInfo.payroll_year}_`
    : '';
  
  // Save the PDF
  doc.save(`Bulk_PAYE_Report_${companyNameSlug}${periodSlug}${new Date().toISOString().split('T')[0]}.pdf`);
};

// Generate CIT Report
export const generateCitReport = (citInput, citResult) => {
  const doc = new jsPDF();
  
  // Prepare company info for header
  const companyInfo = {
    name: citInput.company_name || 'Not specified',
    tin: citInput.tin || null,
    year: citInput.year_of_assessment || citInput.tax_year || 'Not specified'
  };
  
  let yPos = addTaxpayerHeader(doc, 'Corporate Income Tax (CIT) Calculation Report', companyInfo);
  
  // Revenue & Income Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Revenue & Income', 20, yPos);
  yPos += 10;
  
  const revenueData = [
    ['Gross Income/Revenue', formatCurrency(citInput.gross_income)],
    ['Other Income', formatCurrency(citInput.other_income)],
    ['Total Income', formatCurrency(citResult.total_income)]
  ];
  
  autoTable(doc, {
    head: [['Income Component', 'Amount']],
    body: revenueData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [34, 197, 94], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Deductible Expenses Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Deductible Expenses', 20, yPos);
  yPos += 10;
  
  const expenseData = [
    ['Cost of Goods Sold', formatCurrency(citInput.cost_of_goods_sold)],
    ['Staff Costs', formatCurrency(citInput.staff_costs)],
    ['Rent Expenses', formatCurrency(citInput.rent_expenses)],
    ['Professional Fees', formatCurrency(citInput.professional_fees)],
    ['Depreciation', formatCurrency(citInput.depreciation)],
    ['Interest Paid (Unrelated)', formatCurrency(citInput.interest_paid_unrelated)],
    ['Interest Paid (Related)', formatCurrency(citInput.interest_paid_related)],
    ['Other Deductible Expenses', formatCurrency(citInput.other_deductible_expenses)],
    ['Total Deductible Expenses', formatCurrency(citResult.total_deductible_expenses)]
  ];
  
  autoTable(doc, {
    head: [['Expense Component', 'Amount']],
    body: expenseData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [239, 68, 68], textColor: [255, 255, 255] }, // Red header
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Tax Calculation Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('CIT Calculation Summary', 20, yPos);
  yPos += 10;
  
  const citSummaryData = [
    ['Profit Before Loss Relief', formatCurrency((citResult.taxable_profit || 0) + (citResult.carry_forward_losses_applied || 0))],
    ['Loss Relief Applied', formatCurrency(citResult.carry_forward_losses_applied || 0)],
    ['Taxable Profit', formatCurrency(citResult.taxable_profit)],
    ['CIT Rate Applied', `${citResult.cit_rate}%`],
    ['CIT Due', formatCurrency(citResult.cit_due)],
    ['Capital Allowances', formatCurrency(citResult.total_capital_allowances)],
    ['WHT Credits', formatCurrency(citResult.total_wht_credits)],
    ['Net Tax Payable', formatCurrency(citResult.net_tax_payable)],
    ['Development Levy (0.25%)', formatCurrency(citResult.development_levy)]
  ];
  
  autoTable(doc, {
    head: [['Tax Component', 'Amount/Rate']],
    body: citSummaryData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246], textColor: [255, 255, 255] }, // Blue header
    margin: { left: 20, right: 20 }
  });
  
  // Add Capital Allowances breakdown if available
  if (citResult.capital_allowances_breakdown) {
    yPos = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Capital Allowances Breakdown', 20, yPos);
    yPos += 10;
    
    const allowanceData = Object.entries(citResult.capital_allowances_breakdown).map(([key, value]) => [
      key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase()),
      formatCurrency(value)
    ]);
    
    autoTable(doc, {
      head: [['Asset Category', 'Allowance Amount']],
      body: allowanceData,
      startY: yPos,
      theme: 'grid',
      headStyles: { fillColor: [168, 85, 247], textColor: [255, 255, 255] }, // Purple header
      margin: { left: 20, right: 20 }
    });
  }
  
  addFiquantFooter(doc);
  
  // Save the PDF
  doc.save(`CIT_Tax_Report_${citInput.company_name || 'Company'}_${new Date().toISOString().split('T')[0]}.pdf`);
};

// Email CIT Report - sends the report to an email address
export const emailCitReport = async (citInput, citResult, recipientEmail) => {
  const doc = new jsPDF();
  
  // Prepare company info for header
  const companyInfo = {
    name: citInput.company_name || 'Not specified',
    tin: citInput.tin || 'Not specified',
    year: citInput.year_of_assessment || 'Not specified'
  };
  
  let yPos = addTaxpayerHeader(doc, 'Corporate Income Tax Report', companyInfo);
  
  // Company Classification
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Company Classification', 20, yPos);
  yPos += 10;
  
  const classificationData = [
    ['Company Size', citResult.company_size || 'Not determined'],
    ['CIT Rate Applied', `${citResult.cit_rate || 0}%`],
    ['Annual Turnover', formatCurrency(citResult.gross_turnover)]
  ];
  
  autoTable(doc, {
    head: [['Classification', 'Details']],
    body: classificationData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [37, 99, 235], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 10;
  
  // Tax Calculation Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Tax Calculation Summary', 20, yPos);
  yPos += 10;
  
  const taxSummaryData = [
    ['Gross Income', formatCurrency(citResult.gross_income)],
    ['Total Allowable Deductions', formatCurrency(citResult.total_deductions)],
    ['Capital Allowances', formatCurrency(citResult.total_capital_allowances)],
    ['Taxable Profit', formatCurrency(citResult.taxable_profit)],
    ['CIT Payable', formatCurrency(citResult.total_tax_due)]
  ];
  
  autoTable(doc, {
    head: [['Description', 'Amount']],
    body: taxSummaryData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [37, 99, 235], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  // Convert to base64
  const pdfBase64 = doc.output('datauristring').split(',')[1];
  
  // Send to backend for emailing
  const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
  const token = localStorage.getItem('token');
  
  const response = await fetch(`${BACKEND_URL}/api/email/send-report`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`
    },
    body: JSON.stringify({
      recipient_email: recipientEmail,
      report_type: 'CIT',
      report_name: `CIT_Tax_Report_${citInput.company_name || 'Company'}.pdf`,
      pdf_base64: pdfBase64,
      company_name: citInput.company_name || 'Company'
    })
  });
  
  if (!response.ok) {
    throw new Error('Failed to send email');
  }
  
  return await response.json();
};

// VAT Report Generator
export const generateVatReport = (vatInput, vatResult) => {
  const doc = new jsPDF();
  
  // Prepare company info for header
  const companyInfo = {
    name: vatInput.company_name || 'Not specified',
    month: vatInput.month || 'Not specified'
  };
  
  let yPos = addTaxpayerHeader(doc, 'VAT Calculation Report', companyInfo);
  
  // Sales Breakdown
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Sales Breakdown', 20, yPos);
  yPos += 10;
  
  const salesData = [
    ['Total Sales', formatCurrency(vatResult.total_sales)],
    ['VAT Exempt Sales', formatCurrency(vatResult.vat_exempt_sales)],
    ['Zero-Rated Sales (Exports)', formatCurrency(vatResult.zero_rated_sales)],
    ['Taxable Sales', formatCurrency(vatResult.taxable_sales)],
    ['VAT Rate Applied', `${vatResult.vat_rate}%`]
  ];
  
  autoTable(doc, {
    head: [['Sales Component', 'Amount']],
    body: salesData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [34, 197, 94], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // VAT Calculation Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('VAT Calculation Summary', 20, yPos);
  yPos += 10;
  
  const vatSummaryData = [
    ['Total Output VAT Due', formatCurrency(vatResult.output_vat)],
    ['VAT Rate Applied', `${vatResult.vat_rate}%`],
    ['Period', vatResult.month || 'Not specified']
  ];
  
  autoTable(doc, {
    head: [['VAT Component', 'Amount']],
    body: vatSummaryData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  addFiquantFooter(doc);
  
  // Save the PDF
  doc.save(`VAT_Report_${vatInput.company_name || 'Company'}_${vatInput.month || 'Report'}_${new Date().toISOString().split('T')[0]}.pdf`);
};

// Payment Processing Report Generator
export const generatePaymentProcessingReport = (paymentInput, paymentResult) => {
  const doc = new jsPDF();
  
  // Prepare payee info for header
  const payeeInfo = {
    name: paymentResult.payee_name || 'Not specified',
    month: paymentResult.month || 'Not specified',
    year: paymentResult.year || 'Not specified'
  };
  
  let yPos = addTaxpayerHeader(doc, 'Payment Advice (For WHT deduction computation)', payeeInfo);
  
  // Add Transaction Details Section
  if (paymentResult.transaction_details || paymentResult.payee_email) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Transaction Information', 20, yPos);
    yPos += 10;
    
    const transactionData = [];
    if (paymentResult.transaction_details) {
      transactionData.push(['Transaction Details', paymentResult.transaction_details]);
    }
    if (paymentResult.payee_email) {
      transactionData.push(['Payee Email', paymentResult.payee_email]);
    }
    if (paymentResult.year) {
      transactionData.push(['Year', paymentResult.year]);
    }
    
    if (transactionData.length > 0) {
      autoTable(doc, {
        head: [['Field', 'Information']],
        body: transactionData,
        startY: yPos,
        theme: 'grid',
        headStyles: { fillColor: [99, 102, 241], textColor: [255, 255, 255] },
        margin: { left: 20, right: 20 }
      });
      
      yPos = doc.lastAutoTable.finalY + 15;
    }
  }
  
  // Tax Calculations
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Tax Calculations', 20, yPos);
  yPos += 10;
  
  const taxData = [
    ['Amount Before VAT', formatCurrency(paymentResult.amount_before_vat)],
    ['VAT Applicable', paymentResult.vat_applicable ? 'Yes' : 'No'],
    ['VAT Rate', `${paymentResult.vat_rate}%`],
    ['VAT Amount', formatCurrency(paymentResult.vat_amount)],
    ['WHT Rate', `${paymentResult.wht_rate}%`],
    ['WHT Amount', formatCurrency(paymentResult.wht_amount)]
  ];
  
  autoTable(doc, {
    head: [['Tax Component', 'Amount/Rate']],
    body: taxData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [168, 85, 247], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Payment Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Payment Summary', 20, yPos);
  yPos += 10;
  
  const summaryData = [
    ['Gross Contract Amount', formatCurrency(paymentResult.contract_amount)],
    ['Less: VAT', `-${formatCurrency(paymentResult.vat_amount)}`],
    ['Less: WHT', `-${formatCurrency(paymentResult.wht_amount)}`],
    ['Net Payment to Payee', formatCurrency(paymentResult.net_payment)],
    ['Total Government Remittance', formatCurrency(paymentResult.total_government_remittance)]
  ];
  
  autoTable(doc, {
    head: [['Summary Item', 'Amount']],
    body: summaryData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Remittance Deadlines
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Government Remittance Deadlines', 20, yPos);
  yPos += 10;
  
  const deadlineData = [
    ['VAT Remittance', paymentResult.vat_due_date],
    ['WHT Remittance (FIRS)', paymentResult.wht_due_date],
    ['WHT Remittance (SIRS)', paymentResult.sirs_due_date]
  ];
  
  autoTable(doc, {
    head: [['Tax Type', 'Due Date']],
    body: deadlineData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [239, 68, 68], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  addFiquantFooter(doc);
  
  // Save the PDF
  const fileName = `Payment_Advice_${paymentResult.payee_name || 'Payee'}_${paymentResult.month || 'Month'}_${paymentResult.year || new Date().getFullYear()}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};

// CGT Report Generator
export const generateCgtReport = (cgtInput, cgtResult) => {
  const doc = new jsPDF();
  
  // Prepare taxpayer info for header
  const taxpayerInfo = {
    name: cgtResult.taxpayer_name || 'Not specified',
    year: cgtResult.year || 'Not specified'
  };
  
  let yPos = addTaxpayerHeader(doc, 'Capital Gains Tax Report', taxpayerInfo);
  
  // Asset Transaction Details
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Asset Transaction Details', 20, yPos);
  yPos += 10;
  
  const isLoss = cgtResult.is_loss || cgtResult.capital_gain < 0;
  const transactionData = [
    ['Disposal Proceeds', formatCurrency(cgtResult.disposal_proceeds || cgtResult.net_proceeds)],
    ['Acquisition Cost', formatCurrency(cgtResult.acquisition_cost)],
    ['Improvement Costs', formatCurrency(cgtResult.improvement_costs || cgtResult.allowable_expenses || 0)],
    ['Selling Expenses', formatCurrency(cgtResult.selling_expenses || 0)],
    ['Total Cost', formatCurrency(cgtResult.total_cost)],
    [isLoss ? 'Capital Loss' : 'Capital Gain', formatCurrency(Math.abs(cgtResult.capital_gain))]
  ];
  
  autoTable(doc, {
    head: [['Transaction Component', 'Amount']],
    body: transactionData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [34, 197, 94], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // CGT Calculation
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('CGT Calculation', 20, yPos);
  yPos += 10;
  
  let cgtData = [];
  
  // Helper to clean Naira symbols for PDF compatibility
  const cleanNairaSymbol = (text) => {
    if (!text) return text;
    return text.replace(/₦/g, 'N ').replace(/\u20a6/g, 'N ');
  };
  
  if (cgtResult.is_exempt) {
    cgtData = [
      ['CGT Status', 'EXEMPT'],
      ['Exemption Reason', cleanNairaSymbol(cgtResult.exemption_reason)],
      ['CGT Liability', formatCurrency(0)],
      ['Tax Saved', formatCurrency(cgtResult.tax_saved || 0)]
    ];
  } else if (cgtResult.is_loss || cgtResult.capital_gain < 0) {
    cgtData = [
      ['CGT Status', 'CAPITAL LOSS'],
      ['Loss Amount', formatCurrency(Math.abs(cgtResult.capital_gain || cgtResult.loss_amount || 0))],
      ['CGT Liability', formatCurrency(0)],
      ['Loss Carry Forward', 'Available for future gains']
    ];
  } else {
    const rateDisplay = cgtResult.rate_type === 'flat_30%' ? '30% (Company Rate)' : 
                        `${cgtResult.cgt_rate || 0}% (${cgtResult.rate_type || 'Progressive'})`;
    cgtData = [
      ['Taxable Capital Gain', formatCurrency(cgtResult.capital_gain)],
      ['CGT Rate Applied', rateDisplay],
      ['CGT Liability', formatCurrency(cgtResult.cgt_amount || cgtResult.cgt_liability || 0)]
    ];
  }
  
  autoTable(doc, {
    head: [['CGT Component', 'Amount/Status']],
    body: cgtData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  // Add exemption note if applicable
  if (cgtResult.is_exempt) {
    yPos = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Exemption Information', 20, yPos);
    yPos += 8;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('CGT exemption applies when disposal proceeds < N150M AND capital gains <= N10M', 20, yPos);
    yPos += 5;
    doc.text('within any 12-month period (Nigeria Tax Act 2025).', 20, yPos);
  }
  
  // Add tax rate information
  if (!cgtResult.is_exempt && !(cgtResult.is_loss || cgtResult.capital_gain < 0)) {
    yPos = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Tax Rate Information (NTA 2025)', 20, yPos);
    yPos += 8;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    if (cgtResult.taxpayer_type === 'company') {
      doc.text('Companies: 30% CGT rate (aligned with Corporate Income Tax rate)', 20, yPos);
    } else {
      doc.text('Individuals: Progressive rates (0-25%) based on total income level', 20, yPos);
    }
  }
  
  addFiquantFooter(doc);
  
  // Save the PDF
  doc.save(`CGT_Report_${cgtResult.taxpayer_name || 'Taxpayer'}_${cgtResult.year || 'Report'}_${new Date().toISOString().split('T')[0]}.pdf`);
};