import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// Utility function to format currency for PDF (with proper encoding)
const formatCurrency = (amount) => {
  if (amount === null || amount === undefined || isNaN(amount)) return 'N 0.00'; // Use 'N' for Naira in PDF
  return `N ${parseFloat(amount).toLocaleString('en-NG', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

// Utility function to format date
const formatDate = () => {
  return new Date().toLocaleDateString('en-NG', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
};

// Add taxpayer-focused header
const addTaxpayerHeader = (doc, title, taxpayerInfo) => {
  // Document title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text(title, 20, 20);
  
  // Taxpayer Information Section
  let yPos = 35;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Taxpayer Information', 20, yPos);
  yPos += 8;
  
  // Create taxpayer info table
  const taxpayerData = [];
  if (taxpayerInfo.name) {
    taxpayerData.push(['Taxpayer Name:', taxpayerInfo.name]);
  }
  if (taxpayerInfo.tin) {
    taxpayerData.push(['Tax ID (TIN):', taxpayerInfo.tin]);
  }
  if (taxpayerInfo.month) {
    taxpayerData.push(['Period/Month:', taxpayerInfo.month]);
  }
  if (taxpayerInfo.year) {
    taxpayerData.push(['Year of Assessment:', taxpayerInfo.year]);
  }
  if (taxpayerInfo.state) {
    taxpayerData.push(['State of Residence:', taxpayerInfo.state]);
  }
  
  // Add taxpayer info table
  if (taxpayerData.length > 0) {
    autoTable(doc, {
      startY: yPos,
      head: [],
      body: taxpayerData,
      theme: 'plain',
      styles: {
        fontSize: 10,
        cellPadding: 2
      },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 50 },
        1: { cellWidth: 100 }
      }
    });
    yPos = doc.lastAutoTable.finalY + 10;
  }
  
  // Generated date
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on: ${formatDate()}`, 20, yPos);
  
  // Return the Y position where content should start
  return yPos + 15;
};

// Add Fiquant footnote footer
const addFiquantFooter = (doc) => {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // Add separator line
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 275, 190, 275);
    
    // Fiquant branding footnote
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by Fiquant TaxPro - Nigerian Tax Calculator 2026', 20, 282);
    doc.text('© 2025 Fiquant Consult. All rights reserved.', 20, 287);
    
    // Page number
    doc.text(`Page ${i} of ${pageCount}`, 170, 287);
  }
};

// Generate Single PAYE Report
export const generatePayeReport = (taxInput, result) => {
  const doc = new jsPDF();
  
  // Prepare taxpayer info for header
  const taxpayerInfo = {
    name: taxInput.staff_name || 'Not specified',
    tin: taxInput.tin || null,
    month: taxInput.month || 'Not specified',
    state: taxInput.state_of_residence || 'Not specified'
  };
  
  let yPos = addTaxpayerHeader(doc, 'PAYE Tax Calculation Report', taxpayerInfo);
  
  // Remove the redundant Staff Information Section since it's now in header
  
  // Income Details Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Income Details', 20, yPos);
  yPos += 10;
  
  // Income Details Table
  const incomeData = [
    ['Basic Salary', formatCurrency(taxInput.basic_salary)],
    ['Transport Allowance', formatCurrency(taxInput.transport_allowance)],
    ['Housing Allowance', formatCurrency(taxInput.housing_allowance)],
    ['Meal Allowance', formatCurrency(taxInput.meal_allowance)],
    ['Other Allowances', formatCurrency(taxInput.other_allowances)],
    ['Monthly Gross Income', formatCurrency(result.monthly_gross_income)]
  ];
  
  autoTable(doc, {
    head: [['Income Component', 'Amount']],
    body: incomeData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Relief & Deductions Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Monthly Reliefs & Deductions', 20, yPos);
  yPos += 10;
  
  const reliefData = [
    ['Pension Contribution (8%)', formatCurrency(taxInput.pension_contribution || result.monthly_gross_income * 0.08)],
    ['NHF Contribution (2.5%)', formatCurrency(taxInput.nhf_contribution || result.monthly_gross_income * 0.025)],
    ['Life Insurance Premium', formatCurrency(taxInput.life_insurance_premium)],
    ['Health Insurance Premium', formatCurrency(taxInput.health_insurance_premium)],
    ['NHIS Contribution', formatCurrency(taxInput.nhis_contribution)],
    ['Annual Rent Relief', formatCurrency(result.annual_rent_relief)],
    ['Total Monthly Reliefs', formatCurrency(result.total_reliefs)]
  ];
  
  autoTable(doc, {
    head: [['Relief Component', 'Amount']],
    body: reliefData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Tax Calculation Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Tax Calculation Summary', 20, yPos);
  yPos += 10;
  
  const taxData = [
    ['Annual Gross Income', formatCurrency(result.annual_gross_income)],
    ['Annual Total Reliefs', formatCurrency(result.annual_total_reliefs)],
    ['Annual Taxable Income', formatCurrency(result.annual_taxable_income)],
    ['Annual Tax Due', formatCurrency(result.tax_due)],
    ['Monthly Tax (PAYE)', formatCurrency(result.monthly_tax)],
    ['Monthly Net Income', formatCurrency(result.monthly_net_income)]
  ];
  
  autoTable(doc, {
    head: [['Calculation Component', 'Amount']],
    body: taxData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [34, 197, 94], textColor: [255, 255, 255] }, // Green header
    margin: { left: 20, right: 20 }
  });
  
  // Add tax bracket information if available
  if (result.tax_breakdown && result.tax_breakdown.length > 0) {
    yPos = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Tax Bracket Breakdown', 20, yPos);
    yPos += 10;
    
    const bracketData = result.tax_breakdown.map(bracket => [
      bracket.range,
      `${bracket.rate}%`,
      formatCurrency(bracket.taxable_amount),
      formatCurrency(bracket.tax_amount)
    ]);
    
    autoTable(doc, {
      head: [['Income Range', 'Rate', 'Taxable Amount', 'Tax Amount']],
      body: bracketData,
      startY: yPos,
      theme: 'grid',
      headStyles: { fillColor: [59, 130, 246], textColor: [255, 255, 255] }, // Blue header
      margin: { left: 20, right: 20 }
    });
  }
  
  addFiquantFooter(doc);
  
  // Save the PDF
  doc.save(`PAYE_Tax_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};

// Generate Bulk PAYE Report
export const generateBulkPayeReport = (employees, totals) => {
  const doc = new jsPDF();
  
  let yPos = addHeader(doc, 'Bulk PAYE Tax Calculation Report');
  
  // Summary Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Payroll Summary', 20, yPos);
  yPos += 10;
  
  const summaryData = [
    ['Total Employees Processed', totals.employeeCount.toString()],
    ['Total Monthly Gross Pay', formatCurrency(totals.totalGross)],
    ['Total Monthly Tax (PAYE)', formatCurrency(totals.totalTax)],
    ['Total Monthly Net Pay', formatCurrency(totals.totalNet)],
    ['Total Annual Tax', formatCurrency(totals.totalTax * 12)]
  ];
  
  autoTable(doc, {
    head: [['Summary Item', 'Amount/Count']],
    body: summaryData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [34, 197, 94], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 20;
  
  // Employee Details Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Employee Tax Details', 20, yPos);
  yPos += 10;
  
  const calculatedEmployees = employees.filter(emp => emp.calculated && emp.result);
  
  const employeeData = calculatedEmployees.map((emp, index) => [
    (index + 1).toString(),
    emp.name,
    emp.tin || 'N/A',
    formatCurrency(emp.result.monthly_gross_income),
    formatCurrency(emp.result.monthly_tax),
    formatCurrency(emp.result.monthly_net_income)
  ]);
  
  autoTable(doc, {
    head: [['#', 'Employee Name', 'TIN', 'Monthly Gross', 'Monthly Tax', 'Monthly Net']],
    body: employeeData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 },
    styles: { fontSize: 8 }
  });
  
  addFiquantFooter(doc);
  
  // Save the PDF
  doc.save(`Bulk_PAYE_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};

// Generate CIT Report
export const generateCitReport = (citInput, citResult) => {
  const doc = new jsPDF();
  
  let yPos = addHeader(doc, 'Corporate Income Tax (CIT) Calculation Report');
  
  // Company Information Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Company Information', 20, yPos);
  yPos += 10;
  
  const companyData = [
    ['Company Name', citInput.company_name || 'N/A'],
    ['Year of Assessment', citInput.year_of_assessment || 'Not specified'],
    ['Tax Year', citInput.tax_year || 'Not specified'],
    ['Annual Turnover', formatCurrency(citInput.annual_turnover)],
    ['Total Fixed Assets', formatCurrency(citInput.total_fixed_assets)],
    ['Company Classification', citResult.company_type || 'N/A'],
    ['Professional Service Firm', citInput.is_professional_service ? 'Yes' : 'No'],
    ['Multinational Enterprise', citInput.is_multinational ? 'Yes' : 'No']
  ];
  
  autoTable(doc, {
    head: [['Company Detail', 'Value']],
    body: companyData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Revenue & Income Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Revenue & Income', 20, yPos);
  yPos += 10;
  
  const revenueData = [
    ['Gross Income/Revenue', formatCurrency(citInput.gross_income)],
    ['Other Income', formatCurrency(citInput.other_income)],
    ['Total Income', formatCurrency(citResult.total_income)]
  ];
  
  autoTable(doc, {
    head: [['Income Component', 'Amount']],
    body: revenueData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [34, 197, 94], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Deductible Expenses Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Deductible Expenses', 20, yPos);
  yPos += 10;
  
  const expenseData = [
    ['Cost of Goods Sold', formatCurrency(citInput.cost_of_goods_sold)],
    ['Staff Costs', formatCurrency(citInput.staff_costs)],
    ['Rent Expenses', formatCurrency(citInput.rent_expenses)],
    ['Professional Fees', formatCurrency(citInput.professional_fees)],
    ['Depreciation', formatCurrency(citInput.depreciation)],
    ['Interest Paid (Unrelated)', formatCurrency(citInput.interest_paid_unrelated)],
    ['Interest Paid (Related)', formatCurrency(citInput.interest_paid_related)],
    ['Other Deductible Expenses', formatCurrency(citInput.other_deductible_expenses)],
    ['Total Deductible Expenses', formatCurrency(citResult.total_deductible_expenses)]
  ];
  
  autoTable(doc, {
    head: [['Expense Component', 'Amount']],
    body: expenseData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [239, 68, 68], textColor: [255, 255, 255] }, // Red header
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Tax Calculation Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('CIT Calculation Summary', 20, yPos);
  yPos += 10;
  
  const citSummaryData = [
    ['Profit Before Loss Relief', formatCurrency((citResult.taxable_profit || 0) + (citResult.carry_forward_losses_applied || 0))],
    ['Loss Relief Applied', formatCurrency(citResult.carry_forward_losses_applied || 0)],
    ['Taxable Profit', formatCurrency(citResult.taxable_profit)],
    ['CIT Rate Applied', `${citResult.cit_rate}%`],
    ['CIT Due', formatCurrency(citResult.cit_due)],
    ['Capital Allowances', formatCurrency(citResult.total_capital_allowances)],
    ['WHT Credits', formatCurrency(citResult.total_wht_credits)],
    ['Net Tax Payable', formatCurrency(citResult.net_tax_payable)],
    ['Development Levy (0.25%)', formatCurrency(citResult.development_levy)]
  ];
  
  autoTable(doc, {
    head: [['Tax Component', 'Amount/Rate']],
    body: citSummaryData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246], textColor: [255, 255, 255] }, // Blue header
    margin: { left: 20, right: 20 }
  });
  
  // Add Capital Allowances breakdown if available
  if (citResult.capital_allowances_breakdown) {
    yPos = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Capital Allowances Breakdown', 20, yPos);
    yPos += 10;
    
    const allowanceData = Object.entries(citResult.capital_allowances_breakdown).map(([key, value]) => [
      key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase()),
      formatCurrency(value)
    ]);
    
    autoTable(doc, {
      head: [['Asset Category', 'Allowance Amount']],
      body: allowanceData,
      startY: yPos,
      theme: 'grid',
      headStyles: { fillColor: [168, 85, 247], textColor: [255, 255, 255] }, // Purple header
      margin: { left: 20, right: 20 }
    });
  }
  
  addFiquantFooter(doc);
  
  // Save the PDF
  doc.save(`CIT_Tax_Report_${citInput.company_name || 'Company'}_${new Date().toISOString().split('T')[0]}.pdf`);
};

// VAT Report Generator
export const generateVatReport = (vatInput, vatResult) => {
  const doc = new jsPDF();
  
  addHeader(doc, 'VAT Calculation Report');
  
  let yPos = 55;
  
  // Report Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('Value Added Tax (VAT) Report', 20, yPos);
  yPos += 10;
  
  // Generated date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on: ${formatDate()}`, 20, yPos);
  yPos += 20;
  
  // Company Information
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('Company Information', 20, yPos);
  yPos += 10;
  
  const companyData = [
    ['Company Name', vatInput.company_name],
    ['Reporting Month', vatInput.month],
    ['VAT Registration Status', vatInput.is_registered_business ? 'Registered' : 'Not Registered'],
    ['Report Date', formatDate()]
  ];
  
  autoTable(doc, {
    head: [['Company Detail', 'Value']],
    body: companyData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Sales Breakdown
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Sales Breakdown', 20, yPos);
  yPos += 10;
  
  const salesData = [
    ['Total Sales', formatCurrency(vatResult.total_sales)],
    ['VAT Exempt Sales', formatCurrency(vatResult.vat_exempt_sales)],
    ['Zero-Rated Sales (Exports)', formatCurrency(vatResult.zero_rated_sales)],
    ['Taxable Sales', formatCurrency(vatResult.taxable_sales)],
    ['VAT Rate Applied', `${vatResult.vat_rate}%`]
  ];
  
  autoTable(doc, {
    head: [['Sales Component', 'Amount']],
    body: salesData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [34, 197, 94], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // VAT Calculation Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('VAT Calculation Summary', 20, yPos);
  yPos += 10;
  
  const vatSummaryData = [
    ['Output VAT (VAT Collected)', formatCurrency(vatResult.output_vat)],
    ['Input VAT (VAT Recoverable)', formatCurrency(vatResult.input_vat_recoverable)],
    [vatResult.is_refund ? 'VAT Refund Due' : 'Net VAT Payable', formatCurrency(Math.abs(vatResult.net_vat_payable))],
    ['Position', vatResult.is_refund ? 'Refund Position' : 'Payable Position']
  ];
  
  autoTable(doc, {
    head: [['VAT Component', 'Amount']],
    body: vatSummaryData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  addFiquantFooter(doc);
  
  // Save the PDF
  doc.save(`VAT_Report_${vatInput.company_name || 'Company'}_${vatInput.month || 'Report'}_${new Date().toISOString().split('T')[0]}.pdf`);
};

// Payment Processing Report Generator
export const generatePaymentProcessingReport = (paymentInput, paymentResult) => {
  const doc = new jsPDF();
  
  addHeader(doc, 'Payment Processing Report');
  
  let yPos = 55;
  
  // Report Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('Payment Processing & Tax Deduction Report', 20, yPos);
  yPos += 10;
  
  // Generated date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on: ${formatDate()}`, 20, yPos);
  yPos += 20;
  
  // Payment Information
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('Payment Information', 20, yPos);
  yPos += 10;
  
  const paymentData = [
    ['Payee Name/Company', paymentResult.payee_name],
    ['Contract Amount', formatCurrency(paymentResult.contract_amount)],
    ['Transaction Type', paymentResult.transaction_type],
    ['Payee Status', paymentResult.is_resident ? 'Resident' : 'Non-Resident'],
    ['Processing Month', paymentResult.month]
  ];
  
  autoTable(doc, {
    head: [['Payment Detail', 'Value']],
    body: paymentData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Tax Calculations
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Tax Calculations', 20, yPos);
  yPos += 10;
  
  const taxData = [
    ['Amount Before VAT', formatCurrency(paymentResult.amount_before_vat)],
    ['VAT Applicable', paymentResult.vat_applicable ? 'Yes' : 'No'],
    ['VAT Rate', `${paymentResult.vat_rate}%`],
    ['VAT Amount', formatCurrency(paymentResult.vat_amount)],
    ['WHT Rate', `${paymentResult.wht_rate}%`],
    ['WHT Amount', formatCurrency(paymentResult.wht_amount)]
  ];
  
  autoTable(doc, {
    head: [['Tax Component', 'Amount/Rate']],
    body: taxData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [168, 85, 247], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Payment Summary
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Payment Summary', 20, yPos);
  yPos += 10;
  
  const summaryData = [
    ['Gross Contract Amount', formatCurrency(paymentResult.contract_amount)],
    ['Less: VAT', `-${formatCurrency(paymentResult.vat_amount)}`],
    ['Less: WHT', `-${formatCurrency(paymentResult.wht_amount)}`],
    ['Net Payment to Payee', formatCurrency(paymentResult.net_payment)],
    ['Total Government Remittance', formatCurrency(paymentResult.total_government_remittance)]
  ];
  
  autoTable(doc, {
    head: [['Summary Item', 'Amount']],
    body: summaryData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Remittance Deadlines
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Government Remittance Deadlines', 20, yPos);
  yPos += 10;
  
  const deadlineData = [
    ['VAT Remittance', paymentResult.vat_due_date],
    ['WHT Remittance (FIRS)', paymentResult.wht_due_date],
    ['WHT Remittance (SIRS)', paymentResult.sirs_due_date]
  ];
  
  autoTable(doc, {
    head: [['Tax Type', 'Due Date']],
    body: deadlineData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [239, 68, 68], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  addFiquantFooter(doc);
  
  // Save the PDF
  doc.save(`Payment_Processing_Report_${paymentResult.payee_name || 'Payee'}_${paymentResult.month || 'Report'}_${new Date().toISOString().split('T')[0]}.pdf`);
};

// CGT Report Generator
export const generateCgtReport = (cgtInput, cgtResult) => {
  const doc = new jsPDF();
  
  addHeader(doc, 'Capital Gains Tax Report');
  
  let yPos = 55;
  
  // Report Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('Capital Gains Tax (CGT) Report', 20, yPos);
  yPos += 10;
  
  // Generated date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on: ${formatDate()}`, 20, yPos);
  yPos += 20;
  
  // Taxpayer Information
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('Taxpayer Information', 20, yPos);
  yPos += 10;
  
  const taxpayerData = [
    ['Taxpayer Name', cgtResult.taxpayer_name],
    ['Tax Year', cgtResult.year],
    ['Taxpayer Type', cgtResult.taxpayer_type.charAt(0).toUpperCase() + cgtResult.taxpayer_type.slice(1)],
    ['Asset Type', cgtResult.asset_type],
    ['Holding Period', cgtInput.holding_period || 'Not specified']
  ];
  
  autoTable(doc, {
    head: [['Taxpayer Detail', 'Value']],
    body: taxpayerData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // Asset Transaction Details
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Asset Transaction Details', 20, yPos);
  yPos += 10;
  
  const transactionData = [
    ['Disposal Proceeds', formatCurrency(cgtResult.disposal_proceeds)],
    ['Acquisition Cost', formatCurrency(cgtResult.acquisition_cost)],
    ['Allowable Expenses', formatCurrency(cgtResult.allowable_expenses)],
    ['Total Cost', formatCurrency(cgtResult.total_cost)],
    [cgtResult.is_loss ? 'Capital Loss' : 'Capital Gain', formatCurrency(Math.abs(cgtResult.capital_gain))]
  ];
  
  autoTable(doc, {
    head: [['Transaction Component', 'Amount']],
    body: transactionData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [34, 197, 94], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  yPos = doc.lastAutoTable.finalY + 15;
  
  // CGT Calculation
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('CGT Calculation', 20, yPos);
  yPos += 10;
  
  let cgtData = [];
  
  if (cgtResult.is_exempt) {
    cgtData = [
      ['CGT Status', 'EXEMPT'],
      ['Exemption Reason', cgtResult.exemption_reason],
      ['CGT Liability', formatCurrency(0)]
    ];
  } else if (cgtResult.is_loss) {
    cgtData = [
      ['CGT Status', 'CAPITAL LOSS'],
      ['Loss Amount', formatCurrency(cgtResult.loss_amount)],
      ['CGT Liability', formatCurrency(0)],
      ['Loss Carry Forward', 'Available for future gains']
    ];
  } else {
    cgtData = [
      ['Taxable Capital Gain', formatCurrency(cgtResult.capital_gain)],
      ['CGT Rate Applied', cgtResult.rate_description],
      ['CGT Liability', formatCurrency(cgtResult.cgt_liability)]
    ];
  }
  
  autoTable(doc, {
    head: [['CGT Component', 'Amount/Status']],
    body: cgtData,
    startY: yPos,
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246], textColor: [255, 255, 255] },
    margin: { left: 20, right: 20 }
  });
  
  // Add exemption note if applicable
  if (cgtResult.is_exempt) {
    yPos = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Exemption Information', 20, yPos);
    yPos += 8;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('CGT exemption applies when disposal proceeds < N150M AND capital gains < N10M', 20, yPos);
    yPos += 5;
    doc.text('within any 12-month period (Nigerian Tax Act 2026).', 20, yPos);
  }
  
  // Add tax rate information
  if (!cgtResult.is_exempt && !cgtResult.is_loss) {
    yPos = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Tax Rate Information (NTA 2026)', 20, yPos);
    yPos += 8;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    if (cgtResult.taxpayer_type === 'company') {
      doc.text('Companies: 30% CGT rate (aligned with Corporate Income Tax rate)', 20, yPos);
    } else {
      doc.text('Individuals: Progressive rates (0-25%) based on total income level', 20, yPos);
    }
  }
  
  addFiquantFooter(doc);
  
  // Save the PDF
  doc.save(`CGT_Report_${cgtResult.taxpayer_name || 'Taxpayer'}_${cgtResult.year || 'Report'}_${new Date().toISOString().split('T')[0]}.pdf`);
};